---
- name: Manage packages on Ubuntu Node
  hosts: ubuntuNode1
  gather_facts: false
  tasks:
    - name: Install packages using pacman
      community.general.pacman:
        name:
          - flatpak
          - yay
          - mpv
          - ripgrep
          - ffmpegthumbnailer
          - mediainfo
          - wezterm
          - yazi
          - stow
          - zoxide
          - atuin
          - kitty
          - fontforge
          - bat
          - fd
          - fzf
          - nushell
          - vim-ansible
          - tmux
          - xsel
          - httpie
          - rye
          - ollama
          - glow
          - miller
          - ouch
          - rsync
          - rust-analyzer
          - ttyper
        state: present
      become: yes

    # - name: Install AUR packages using yay
    #   ansible.builtin.command:
    #     cmd: yay -Syu --noconfirm yaak-app snapd google-chrome-dev archivemount neovim-git tabby-bin ruby-colorls httpie-desktop-appimage
    #   become: no

    - name: Install Flatpak applications
      community.general.flatpak:
        name:
          - io.github.zen_browser.zen
          - com.obsproject.Studio
          - md.obsidian.Obsidian
          - one.ablaze.floorp
          - dev.zed.Zed
        state: present
      become: yes

    # - name: Install snap classic packages
    #   community.general.snap:
    #     name:
    #       - code
    #     classic: true

    - name: Install snap packages
      community.general.snap:
        name:
          - pieces-os
          - pieces-for-developers
          - discord
          - spotify
          - notesnook
          - brave
          - postman
          - telegram-desktop
# posting
