
# Use the official image as a parent image
FROM ubuntu

# Update the system, install OpenSSH Server, and set up users
RUN apt-get update && apt-get upgrade -y && \
  apt-get install -y openssh-server && apt-get install sudo -y

# Create user and set password for user and root user
RUN  useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 ubuntu && \
  echo 'ubuntu:BuDTuT@143' | chpasswd && \
  echo 'root:BuDTuT@143' | chpasswd

# Set up configuration for SSH
RUN mkdir /var/run/sshd && \
  sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
  sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
  echo "export VISIBLE=now" >> /etc/profile

WORKDIR /home/ubuntu
RUN sudo apt-get install software-properties-common -y
RUN sudo apt-get install build-essential -y


# install neovim
# Replace with "nightly" for nightly version
ENV NEO_VERSION=stable  
ENV NEO_URL="https://github.com/neovim/neovim/releases/download/${NEO_VERSION}/nvim-linux64.tar.gz"

RUN wget ${NEO_URL}

# create .local directory if doesnt exist and extract "nvim-linux64.tar.gz" to .local/nvim
RUN mkdir -p .local/nvim && tar xvf nvim-linux64.tar.gz

RUN mv nvim-linux64/* /home/ubuntu/.local/nvim/


# install git
RUN add-apt-repository ppa:git-core/ppa
RUN apt-get update
RUN apt-get install -y git


# remove nvim-linux64.tar.gz
RUN rm -rf nvim-linux64.tar.gz nvim-linux64


# Expose the SSH port
EXPOSE 22

# Run SSH
CMD ["/usr/sbin/sshd", "-D"]

